### ISSUE TITLE
Request: Template and Structure for General/Contract Information

### ISSUE THREAD

**Issue by decentdanoz** [HebePlatform/ETCScanList#1]
"0x1FDc495289B590e78d455cf7faa6cd804de5Cbc1": {
    "name": "Shiba Classic",
    "links": {
      "web": "https://shibaclassic.sc",
      "twitter": "https://twitter.com/shibctokenetc",
      "discord": "https://discord.gg/Rz7bN3ZaeM",
      "telegram": "https://t.me/ShibCtokenERC",
      "email": "shibaclassicetc@gmail.com"
    }
  }

**Comment by decentdanoz** [comment]
Hi HebePlatform! Fantastic work with this.

Unsure if to make a PR for list.json, or if a folder structure is better, to then update with.

**Comment by HebeBlock** [comment]
> Hi HebePlatform! Fantastic work with this.
> 
> Unsure if to make a PR for list.json, or if a folder structure is better, to then update with.


Currently, there are not many projects in ETC. We'll use json to keep it relatively simple.

**Comment by decentdanoz** [comment]
> Currently, there are not many projects in ETC

Completely understood. It's very lucky to be so early with you guys doing so much good work.

![image](https://user-images.githubusercontent.com/70056410/201568058-f8228663-1b46-410e-9f56-8b1670627371.png)

Even since the most recent tweet, activity is picking right up, so I have made the fork with the structure and templates for when we get very busy and if they're ever needed.

Thank you again, you're doing awesome work for ETC. I will close this out.
