### ISSUE TITLE
General site issues

### ISSUE THREAD

**Issue by bosinupebi** [HebePlatform/ETCScanList#3]
1. Spelling of Scan on this screen
<img width="1327" alt="Screen Shot 2022-11-14 at 2 16 04 AM" src="https://user-images.githubusercontent.com/47193697/201598182-d8091de7-adc6-4562-b479-5b26575cfe05.png">

2. Search filter dropdown options do not appear to be visible
<img width="725" alt="Screen Shot 2022-11-14 at 2 18 32 AM" src="https://user-images.githubusercontent.com/47193697/201598461-dc98130e-ef66-4e39-95d7-5529595fcea0.png">

**Comment by HebeBlock** [comment]
Hi, thanks for your feedback, we will revise the spelling on etcdesktop.
Search by condition is currently made into an aggregate, and in the future, we will consider whether to search by condition

**Comment by bosinupebi** [comment]
Thanks
